import type { ReactNode } from 'react'
import { Button, Card, Media, Section } from './components'
import type { Action, CtaSectionDefinition, FeatureGridSectionDefinition, HeroSectionDefinition, SectionComponent, SectionDefinition } from './types'

function Actions({ actions }: { actions?: Action[] }) { return actions?.length ? <div className="engine-actions">{actions.map((action) => <Button key={`${action.href}-${action.label}`} variant={action.type === 'secondary' ? 'secondary' : 'primary'} href={action.href} target={action.target} aria-label={action.ariaLabel}>{action.label}</Button>)}</div> : null }
function Heading({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <header className="engine-section-heading">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{description && <p>{description}</p>}</header> }
export const HeroSection: SectionComponent<HeroSectionDefinition> = ({ section }) => <Section className={`engine-hero engine-hero--${section.variant ?? 'default'} ${section.settings?.className ?? ''}`} id={section.settings?.id}><div className="engine-hero__copy">{section.eyebrow && <p className="eyebrow">{section.eyebrow}</p>}<h1>{section.title}</h1>{section.description && <p>{section.description}</p>}<Actions actions={section.actions} /></div>{section.media && <Media {...section.media} />}</Section>
export const FeatureGridSection: SectionComponent<FeatureGridSectionDefinition> = ({ section }) => <Section className={`engine-feature-grid engine-feature-grid--${section.variant ?? 'cards'} ${section.settings?.className ?? ''}`} id={section.settings?.id}><Heading eyebrow={section.eyebrow} title={section.title} description={section.description} /><div className="engine-feature-grid__items">{section.items.map((item) => <Card key={item.title}>{item.media && <Media {...item.media} />}<h3>{item.title}</h3>{item.description && <p>{item.description}</p>}{item.href && <a href={item.href}>{item.href}</a>}</Card>)}</div></Section>
export const ContentSection: SectionComponent<Extract<SectionDefinition, { type: 'content' }>> = ({ section }) => <Section className={`engine-content engine-content--${section.variant ?? 'default'} ${section.settings?.className ?? ''}`} id={section.settings?.id}><Heading eyebrow={section.eyebrow} title={section.title} /><p>{section.body}</p><Actions actions={section.actions} /></Section>
export const ProcessSection: SectionComponent<Extract<SectionDefinition, { type: 'process' }>> = ({ section }) => <Section className={`engine-process ${section.settings?.className ?? ''}`} id={section.settings?.id}><Heading eyebrow={section.eyebrow} title={section.title} /><ol>{section.steps.map((step, index) => <li key={`${index + 1}-${step.title}`}><span>{String(index + 1).padStart(2, '0')}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol></Section>
export const FaqSection: SectionComponent<Extract<SectionDefinition, { type: 'faq' }>> = ({ section }) => <Section className={`engine-faq ${section.settings?.className ?? ''}`} id={section.settings?.id}><Heading eyebrow={section.eyebrow} title={section.title} /><div>{section.items.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></Section>
export const CtaSection: SectionComponent<CtaSectionDefinition> = ({ section }) => <Section className={`engine-cta engine-cta--${section.variant ?? 'default'} ${section.settings?.className ?? ''}`} id={section.settings?.id}><Heading eyebrow={section.eyebrow} title={section.title} description={section.description} /><Actions actions={section.actions} /></Section>
export type Renderable = ReactNode
